name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
# We need some inputs for the AWS and bucket
inputs:
  bucket:
    description: 'The S3 Bucket name'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the deployable files'
    required: true
runs:
  using: 'node16' # Custom java script action
  main: 'main.js' # We indicate the path for the file we created (since its in the same path, no further ado)
  # Action will use the script and logic in this file